---
title: "ch1DataViz"
author: "Charles Di Renzo"
date: '2023-08-31'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#working through chapter 1 of the book R for Data Science by Hadley Wickham and Garrett Grolemund
```{r}

library(tidyverse)

mpg
```

This plot shows the negative relationship between engine size (displ) and feul efficiency (hwy)
```{r}
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy))

```
Exercises and creating a reusable template for making graphs with ggplot2. 
```{r}
#ggplot(data = <DATA>) + <GEOM_FUNCTION>(mapping = aes(<MAPPINGS>))

dim(mpg)


```
?mpg
```{r}


ggplot(mpg, aes(x=cyl, y=hwy)) + 
  geom_point() + 
  ggtitle("Scatterplot of Highway MPG vs Number of Cylinders") +
  xlab("Number of Cylinders") +
  ylab("Highway MPG")


ggplot(mpg, aes(x=class, y=drv)) +
  geom_jitter(width = 0.2, height = 0.2) +
  ggtitle("Scatterplot of Vehicle Class vs Drive Type") +
  xlab("Vehicle Class") +
  ylab("Drive Type")
```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```